# Site wide configuration
source                  : .tmp/src
destination             : .tmp/dist

title			: "Odd One Out"
description		: "My blog about geeky projects"
logo			: ""
teaser			: ""
locale			: "en_US"
words_per_minute        : 200

repository              : "psirek/Ox3-test"
url                     : "https://odd-one-out-serek-eu.netlify.com"
baseurl                 : "" # This breaks a few links since {{ site.baseurl }} is not prefixed. Using custom domain (CNAME file in root) with GitHub Pages (gh-pages) and Cloudflare (CNAME record) does work though

social:
  name                  : "Poul Serek"
  links:
    - "https://twitter.com/psirek"
    - "https://www.facebook.com/Odd-One-Out-Serekeu-850332811727698/"
    - "https://github.com/psirek"
    - "https://plus.google.com/u/0/+PoulSerek"

google_site_verification : "bWPdzXDa220Nz0LNBLuGBY1gBb4DVapoIDm02z0v3HI"
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : ""

google_ad-client         : ""
google_ad-slot           : ""
# google_analytics         : "" # Disabled because of GDPR - UA-46921389-1

feed:
  path                  : "/atom.xml"

favicon_version         : "5A54z5oklP"

pingback_url            : ""
webmention_url          : ""

# Site owner
author:
  name                   : "Poul Serek" # Also used for copyright name if copyright variable is not not set
  uri                    : &uri "https://Ox3.serek.eu/about/"
  url                    : *uri
  bio                    : "Todo."
  picture                : "/assets/images/todo.jpg"
  twitter                : "https://twitter.com/psirek"
  facebook               : 
  instagram              : 
  tumblr                 : 
  github                 : "https://github.com/psirek"
  google_plus            : "https://plus.google.com/u/0/+PoulSerek"

twitter:
  username               : "psirek"

# Staticman comments (full configuration in staticman.yml)
#staticman:
#  branch                 : "master"

# reCAPTCHA keys
#reCaptcha:
#  siteKey: "6LchDDIUAAAAAG8oaPZ0uijNaFXHMcEpef0hbYHS"
#  secret: "xU3bCzZxRFZ61ORS+A1vcAaE8LqsPt4QzjzqAWBOy68k8mL8+dkNJsPmAIkV5PQwkYVYXU4+FlkPlTbgG3Af5Snrs0l8cx70ASvvge4aGDdq8Rq3Z7GVs4/As9KaJEsQbdlyIubEXCflvl6ich7YoASUw/twx/iqx9Sj1wS8K40="

# Jekyll configuration
permalink                : /:categories/:title/
lsi                      : true
future                   : false
show_drafts              : false
markdown                 : kramdown
kramdown:
  toc_levels             : 1..3
  input                  : GFM
  hard_wrap              : false
  auto_ids               : true
  entity_output          : as_char
  smart_quotes           : lsquo,rsquo,ldquo,rdquo
  enable_coderay         : false
highlighter              : rouge
strict_front_matter      : true
keep_files:
  - .git
include:
  - _pages
  - _redirects
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Capfile
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-typogrify
  - jekyll/figure
  - jekyll-algolia
  - jekyll-redirect-from
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-include-cache
  - jekyll-toc

# Collections
collections:
  components:
    output    : false
  colors:
    output    : false

# Front Matter Defaults
defaults:
  # Projects
  - scope:
      path: _posts/projects
      type: posts
    values:
      layout: post
      category: projects
      read_time: true
      comments: false
      support: true
      breadcrumbs:
        - label: "Projects"
          url: /projects/
  # Reviews
  - scope:
      path: _posts/reviews
      type: posts
    values:
      layout: post
      category: reviews
      read_time: true
      comments: false
      support: true
      breadcrumbs:
        - label: "Reviews"
          url: /reviews/
  # Code
  - scope:
      path: _posts/code
      type: posts
    values:
      layout: post
      category: code
      read_time: true
      comments: false
      support: false
      breadcrumbs:
        - label: "Code"
          url: /code/
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  debug: false
  per_page: 15
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "autopage_tags.html"
    title      : ":tag" # :tag is replaced by the tag name
    permalink  : "/tag/:tag"

# Plugin: Table of Contents (jekyll-toc)
toc:
  min_level: 2
  max_level: 2
  list_class: "toc__menu"
  item_class: "toc__entry"
  item_prefix: "toc__"

# Plugin: Jekyll Algolia
algolia:
  application_id: AT2QV5B6I7
  index_name: Odd_one_out
  search_only_api_key: 9847b42e8dd3514fed0bcc9d1d522c95
  nodes_to_index: "p"
  files_to_exclude:
    - index.html
    - index.md
    - _pages/404.md
