---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/_pages
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: ".md"
- type: directory
  path: src/_posts
  label: Posts
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: src/assets/images/feature
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
